fd/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fd_controller:
      type: effort_controllers/JointGroupEffortController # ForwardCommandController

    fd_ee_broadcaster:
      type: ee_pose_broadcaster/EePoseBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fd/fd_controller:
  ros__parameters:
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    joints:
      - fd_x
      - fd_y
      - fd_z
    ## Note: uncomment the following if using an omega 7 device (e.g., 7 controlled DoF)
      # - fd_roll
      # - fd_pitch
      # - fd_yaw
    ## Note: uncomment the following if a clutch is present (e.g., omega 6/7 device)
      # - fd_clutch

fd/fd_ee_broadcaster:
  ros__parameters:
    transform_translation:
      - 0.0
      - 0.0
      - 0.0
    transform_rotation:
      - 0.0
      - 0.0
      - 0.0
    joints:
      - fd_x
      - fd_y
      - fd_z
    ## Note: uncomment the following if orientation is enabled (e.g., omega 6/7 device)
      # - fd_roll
      # - fd_pitch
      # - fd_yaw
    buttons: [button]  # Note: only one button supported for now
